---
title: "rate_change"
author: "Mohd Azmi"
date: "01/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(ggplot2)
```

# Average Rate of Change

```{r}
ratechange <- read_csv("ratechange.csv")
ratechange
```

```{r}
ratechange$Particular <- factor(ratechange$Particular, levels = c("05/03_18/03", "07/03_18/03", "05/03_01/04", "07/03_01/04", "19/03_01/04", "01/04"))
ratechange$misc <- factor(ratechange$misc, levels = c("1st malaysian - MCO", "1st local transmission - MCO", "1st malaysian - EMCO", "1st local transmission - EMCO", "MCO - EMCO", "Today"))
ggplot(ratechange, aes(Average_Rate, x=Particular, fill = misc, label = Average_Rate, digit=2)) +
  geom_col() + xlab("Duration") + ylab("Average Case per Day") +
  theme_minimal() + geom_text()

```

```{r, eval=F}
#ggsave("changeplot.png", plot = last_plot(), width = 4^1.5, height = 3^1.5, dpi = 320)
```

# Weekly Cases

```{r}
numcaseperweek <- read_csv("numcaseperweek.csv")
numcaseperweek
```

```{r}
numcaseperweek$Date <- factor(numcaseperweek$Date, levels = c("24/01-25/01", "26/01-01/02", "02/02-08/02", "09/02-15/02", "16/02-22/02", "23/02-29/02", "01/03-07/03", "08/03-14/03", "15/03-21/03", "22/03-28/03", "29/03-01/04"))
ggplot(numcaseperweek) +
  geom_col(aes(x=EpidWeek, y=Rate, fill = Date)) +
  scale_x_continuous(breaks = seq(0,20,1)) +
  geom_text(aes(x=EpidWeek, y=Rate, label = Rate), nudge_y = 10) +
  geom_text(aes(x=EpidWeek, y=Rate, label = misc), nudge_y = 20, size = 3, check_overlap = T) +
  ylab("Average New Case per Day\nIn Particular Week") + theme_bw()
```

```{r, eval=F}
#ggsave("weekchangeplot.png", plot = last_plot(), width = 4^1.5, height = 3^1.5, dpi = 320)
```

##test
```{r}
ggplot(numcaseperweek) +
  geom_col(aes(x=EpidWeek, y=log(Rate, 10), fill = Date)) +
  scale_x_continuous(breaks = seq(0,20,1)) +
  ylab("Average New Case per Day\nIn Particular Week") + theme_bw()
```

```{r}
ggplot(numcaseperweek, aes(x= EpidWeek, y=Rate)) +
  geom_point() + geom_smooth()
```

