---
title: "COVID19 MY 17032020"
author: "Mohd Azmi"
date: "19/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Environment

## package

```{r}
library(pacman)
p_load(tidyverse, summarytools)
```


from outbreak.my
retrieve 18/03/2020

```{r}
library(readr)
mycase <- read_csv("MY_case_list_upto17032020.csv", 
    col_types = cols(Confirmed_Date = col_date(format = "%d/%m/%Y"), 
        X9 = col_skip()))
mycase
```

# Analysis

## count case per day

```{r}
casecount <- mycase %>% group_by(Confirmed_Date) %>% count()
casecount
#write.csv(casecount, "casecount.csv")
```

## plot 

```{r}
old <- par(mfrow = c(1,2))
plot(casecount, type = "b")
plot(casecount, log = "y")
abline(lm(log10(casecount$n) ~ casecount$Confirmed_Date))
```

## case by state

```{r}
mycase %>% group_by(State) %>% count()
```

# SIR

from https://blog.ephorie.de/covid-19-the-case-of-germany

```{r}
casecount3 <- read_csv("casecount3.csv", 
    col_types = cols(Confirmed_Date = col_date(format = "%d/%m/%Y")))

mypop <- 32680000
Infected <- casecount3$Total_Case
Day <- 1:(length(Infected))

p_load(deSolve)

SIR <- function(time, state, parameters) {
  par <- as.list(c(state, parameters))
  with(par, {
    dS <- -beta/mypop * I * S
    dI <- beta/mypop * I * S - gamma * I
    dR <- gamma * I
    list(c(dS, dI, dR))
  })
}

init <- c(S = mypop-Infected[1], I = Infected[1], R = 0)

RSS <- function(parameters) {
  names(parameters) <- c("beta", "gamma")
  out <- ode(y = init, times = Day, func = SIR, parms = parameters)
  fit <- out[ , 3]
  sum((Infected - fit)^2)
}

Opt <- optim(c(0.5, 0.5), RSS, method = "L-BFGS-B", lower = c(0, 0), upper = c(1, 1)) # optimize with some sensible conditions
Opt$message
## [1] "CONVERGENCE: REL_REDUCTION_OF_F <= FACTR*EPSMCH"
 
Opt_par <- setNames(Opt$par, c("beta", "gamma"))
Opt_par
##      beta     gamma 
## 0.6427585 0.3572415
 
t <- 1:80 # time in days
fit <- data.frame(ode(y = init, times = t, func = SIR, parms = Opt_par))
col <- 1:3 # colour
 
matplot(fit$time, fit[ , 2:4], type = "l", xlab = "Day", ylab = "Number of subjects", lwd = 2, lty = 1, col = col)
matplot(fit$time, fit[ , 2:4], type = "l", xlab = "Day", ylab = "Number of subjects", lwd = 2, lty = 1, col = col, log = "y")
## Warning in xy.coords(x, y, xlabel, ylabel, log = log): 1 y value <= 0
## omitted from logarithmic plot
 
points(Day, Infected)
legend("bottomright", c("Susceptibles", "Infecteds", "Recovereds"), lty = 1, lwd = 2, col = col, inset = 0.05)
```

